name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check code
      uses: actions/checkout@v4
    
    - name: run compile check
      run: cc main.c
